fix integer overflow in Unpacker::size_hint()
In Unpacker::size_hint(), lo needs to be positive, so that the result
"(lo * 10 - 9 + 7) / 8" becomes non-negative. Otherwise, lo==0 results
in a negative integer, which causes integer overflow like that.

  thread 'test_decode' panicked at 'attempt to subtract with overflow',
src/lib.rs:282